const PORT = 3001;
const BROADCAST_EVENTS = {
    CAPTURE_RESULT: 'CAPTURE_RESULT',
    LOG_INFO: 'LOG_INFO',
    PLAYER_ADDITION: 'PLAYER_ADDITION',
    PLAYER_LIST: 'PLAYER_LIST'
};
const RECEPTION_EVENTS = {
    CAPTURE_ATTEMPT: 'CAPTURE_ATTEMPT',
    PLAYER_CONNECTION: 'PLAYER_CONNECTION'
};

module.exports = {
    BROADCAST_EVENTS,
    RECEPTION_EVENTS,
    PORT
};